HrmsMgtApp/Controllers/LeavesController.cs
using HrmsMgtApp.Data;
using HrmsMgtApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MimeKit;
using MimeKit.Text;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace HrmsMgtApp.Controllers
{
    [Authorize]
    public class LeavesController : Controller
    {
        private readonly ILeaves _leavesService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILeaveTypes _leaveTypesService;
        private readonly IUnit _unitService;
        private readonly ApplicationDbContext _context;
        private readonly ILeaveUpload _leaveUpload;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public LeavesController(ILeaves leavesService,UserManager<ApplicationUser> userManager,
                                       ILeaveTypes leaveTypesService,IUnit unitService,ApplicationDbContext context,
                                       ILeaveUpload leaveUpload,SignInManager<ApplicationUser> signInManager)
        {
            _leavesService = leavesService;
            _userManager = userManager;
            _leaveTypesService = leaveTypesService;
            _unitService = unitService;
            _context = context;
            _leaveUpload = leaveUpload;
            _signInManager = signInManager;
        }
        // GET: LeavesController

        public async Task<IActionResult> UHLeaveList()
        {
            var user = await _userManager.GetUserAsync(User);

            var result = _leavesService.GetAllLeavesUH(user);

            var indexview = new AdminLeavesIndex()
            {
                TotalLeaves = result.Count(),
                ApprovedRequests=result.Count(result=>result.UHeadStatus==true),
                PendingRequests=result.Count(result=>result.UHeadStatus==null),
                RejectedRequests=result.Count(result=>result.UHeadStatus==false),
                TotalRequests=result.Count(),
                AllLeaves=result
            };


            return View(indexview);
        }

        public async Task<IActionResult> HRLeaveList()
        {
            var user = await _userManager.GetUserAsync(User);

            var result = _leavesService.GetAllLeavesHR();

            var indexView = new HrLeavesIndexVm()
            {
                AllLeaves=result,
                ApprovedRequests=result.Count(res=>res.HRStatus==true),
                PendingRequests=result.Count(res=>res.HRStatus==null),
                RejectedRequests=result.Count(res=>res.HRStatus==false),
                TotalLeaves=result.Count(),
                TotalRequests=result.Count()
            };


            return View(indexView);
        }


        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var check = _leavesService.GetAllLeaves(user);

            return View(check);
        }

        // GET: LeavesController/Details/5
        public IActionResult Details(int id)
        {
            var leaveDetails = _leavesService.GetLeavess(id);
            if (leaveDetails==null)
            {
                ViewBag.ErrorMessage = $"Leaves  with Id={id} cannot be found, Kindly contact the HR or Admin";

                return View("ErrorPage");
            }
            return View(leaveDetails);
        }

        // GET: LeavesController/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);


             ViewData["LeaveTypeId"] = new SelectList(_leaveTypesService.GetAllLeaves(), "Id", "Type");
             ViewData["UnitsId"] = new SelectList(_unitService.GetAllUnits(), "Id", "Name");

            var NormalUsers = (from u in _context.Users
                              join r in _context.UserRoles on u.Id equals r.UserId
                              join s in _context.Roles on r.RoleId equals s.Id
                              where u.Id==r.UserId && (/*s.Name != "HR" || s.Name != "UnitHead" ||*/ s.Name == "User" /*|| s.Name != "SuperAdmin"*/)
                              select new
                              {
                                  Value=r.UserId,
                                  Text=u.FirstName + ' ' + u.LastName
                              }).ToList();

            ViewData["Users"] = new SelectList(NormalUsers, "Value", "Text");

            var checkuserLeaves = _leaveUpload.GetLeaveUser(user);

            var isApplyAlready = _leavesService.GetAllLeaves(user).LastOrDefault();

         

            if (checkuserLeaves==null)
            {
                ViewBag.ErrorMessage = $"Leaves  for user Name = {user.UserName} cannot be found, Kindly contact the HR or Admin";

                return View("ErrorPage");
            }

            if (isApplyAlready==null)
            {
                ViewBag.TotalLeaves = Convert.ToInt32(checkuserLeaves.TotalLeaves);
                ViewBag.RemainingLeaves = Convert.ToInt32(checkuserLeaves.RemainingLeaves);
                ViewBag.OutstandingLeaves = Convert.ToInt32(checkuserLeaves.NumberOfOutstandingLeaves);
                ViewBag.CurrentLeaves = Convert.ToInt32(checkuserLeaves.CurrentLeaveDays);

                var utilizeLeavess = checkuserLeaves.UtilizedLeaves;

                if (ViewBag.RemainingLeaves <= 0 || ViewBag.RemainingLeaves == null)
                {

                    ViewBag.ErrorMessage = $"Leaves  for user Name = {user.UserName} has been exhausted, Kindly contact the HR or Admin";

                    return View("ErrorPage");
                }

                if (utilizeLeavess == null)
                {
                    ViewBag.UtilizeLeaves = 0;
                }
                else
                {
                    ViewBag.UtilizeLeaves = utilizeLeavess;
                }

                return View();
            }

            if (isApplyAlready.UHeadStatus == null || isApplyAlready.UHeadStatus==false)
            {

                ViewBag.ErrorMessage = $"Leaves  for user Name = {user.UserName} have been previously submitted, Kindly contact the HR or Admin for status";

                return View("ErrorPage");
            }


            ViewBag.TotalLeaves = Convert.ToInt32(checkuserLeaves.TotalLeaves);
            ViewBag.RemainingLeaves = Convert.ToInt32(checkuserLeaves.RemainingLeaves);
            ViewBag.OutstandingLeaves = Convert.ToInt32(checkuserLeaves.NumberOfOutstandingLeaves);
            ViewBag.CurrentLeaves = Convert.ToInt32(checkuserLeaves.CurrentLeaveDays);

            var utilizeLeaves = checkuserLeaves.UtilizedLeaves;

            if (ViewBag.RemainingLeaves <= 0 || ViewBag.RemainingLeaves == null)
            {

                ViewBag.ErrorMessage = $"Leaves  for user Name = {user.UserName} has been exhausted, Kindly contact the HR or Admin";

                return View("ErrorPage");
            }

            if (utilizeLeaves == null)
            {
                ViewBag.UtilizeLeaves = 0;
            }
            else
            {
                ViewBag.UtilizeLeaves = utilizeLeaves;
            }



            return View();

           
        }

        // POST: LeavesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Obsolete]
        public async Task<IActionResult> Create(Leave model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var user = await _userManager.GetUserAsync(User);

                    var startDate = Convert.ToDateTime(model.StartDate);
                    var endDate = Convert.ToDateTime(model.EndDate);

                    int weekEnds = NumberOfWeeekends(startDate, endDate);
                    var leaveRequested = (endDate - startDate).Days - weekEnds;

                    var leavetype = _leaveTypesService.GetLeaveType(model.LeaveTypeId);

                    var leaveTypeDays = leavetype.NumberOfDays;

                    var leaveUpload = _leaveUpload.GetLeaveUser(user);
                    var leaveUp = _leaveUpload.GetLeaveUser(user);

                    //if (leavetype.Type== "Annual")
                    //{
                    //    leavetype.NumberOfDays = Convert.ToInt32(leaveUpload.RemainingLeaves);
                    //}
                    if (model.LeaveTypeId != 1)
                    {
                        await _leavesService.Create(model);
                        return RedirectToAction(nameof(Index));
                    }

                    if (Convert.ToInt32(leaveRequested) > Convert.ToInt32(leaveUpload.RemainingLeaves))
                    {
                        ViewBag.ErrorMessage = $"Leaves  for user Name = {user.UserName} has been exhausted or more than requested leave, Kindly contact the HR or Admin";

                        return View("ErrorPage");
                    }


                    leaveUpload.RemainingLeaves = (Convert.ToInt32(leaveUpload.RemainingLeaves) - Convert.ToInt32(leaveRequested)).ToString();
                    leaveUpload.UtilizedLeaves = (Convert.ToInt32(leaveUpload.UtilizedLeaves) + Convert.ToInt32(leaveRequested)).ToString();

                    model.LeaveRemaining = Convert.ToInt32(leaveUpload.RemainingLeaves);
                    model.LeaveUtilized = Convert.ToInt32(leaveUpload.UtilizedLeaves);


                    await _leaveUpload.Update(leaveUpload);

                    await _leavesService.Create(model);


                    //var checkUnitHead = (from U in _context.Users
                    //                     join Ur in _context.UserRoles on U.Id equals Ur.UserId
                    //                     join R in _context.Roles on Ur.RoleId equals R.Id

HrmsMgtApp/Views/Leaves/Delete.cshtml
@model Leave


@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center text-danger">Are you sure you want to delete this?</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back</a>
    </div>
</div>

<div>
   
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate) :
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate) :
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.HRStatus) :
        </dt>
        <dd class="col-sm-10">
            @if (Model.HRStatus == true)
            {
                <span class="custom-badge status-green">Approved</span>
            }
            else if (Model.HRStatus == false)
            {
                <span class="custom-badge status-red">Dissaproved</span>
            }
            else
            {
                <span class="custom-badge status-green">Pending</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UHeadStatus) :
        </dt>
        <dd class="col-sm-10">
            @if (Model.UHeadStatus == true)
            {
                <span class="custom-badge status-green">Approved</span>
            }
            else if (Model.UHeadStatus == false)
            {
                <span class="custom-badge status-red">Dissaproved</span>
            }
            else
            {
                <span class="custom-badge status-green">Pending</span>
            }
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Purpose)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Purpose)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Created) :
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Created)
        </dd>
    </dl>
</div>

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Delete">
            <input asp-for="Id" hidden />
                  

            <div class="m-t-20 text-center">
                <button class="btn btn-danger submit-btn">Delete</button>
            </div>
        </form>
    </div>
</div>
@*<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-rounded"><i class="fa fa-edit"></i> Edit</a>
</div>*@

HrmsMgtApp/Views/Leaves/HRLeaveList.cshtml
@model HrLeavesIndexVm

@{
    ViewData["Title"] = "HRLeaveList";
}

<link href="~/Preclinic-Hospital-Bootstrap4-Admin/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title"></h4>
    </div>
    <div class="col-sm-8 col-9 text-right m-b-20">
        <a asp-action="Create" class="btn btn-primary float-right btn-rounded"><i class="fa fa-plus"></i> Create Leave</a>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
        <div class="dash-widget">
            <span class="dash-widget-bg1"><i class="fa fa-check"></i></span>
            <div class="dash-widget-info text-right">
                <h3>@Model.ApprovedRequests</h3>
                <span class="widget-title1">ApprovedRequests <i class="fa fa-check" aria-hidden="true"></i></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
        <div class="dash-widget">
            <span class="dash-widget-bg2"><i class="fa fa-times-circle" aria-hidden="true"></i></span>
            <div class="dash-widget-info text-right">
                <h3>@Model.RejectedRequests</h3>
                <span class="widget-title2">RejectedRequests <i class="fa fa-check" aria-hidden="true"></i></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
        <div class="dash-widget">
            <span class="dash-widget-bg3"><i class="fa fa-bell-o" aria-hidden="true"></i></span>
            <div class="dash-widget-info text-right">
                <h3>@Model.PendingRequests</h3>
                <span class="widget-title3">PendingRequests <i class="fa fa-check" aria-hidden="true"></i></span>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6 col-xl-3">
        <div class="dash-widget">
            <span class="dash-widget-bg4"><i class="fa fa-columns" aria-hidden="true"></i></span>
            <div class="dash-widget-info text-right">
                <h3>@Model.TotalLeaves</h3>
                <span class="widget-title4">TotalRequests <i class="fa fa-check" aria-hidden="true"></i></span>
            </div>
        </div>
    </div>
    <hr />


</div>


@if (Model.AllLeaves.Any())
{
    <div class="col-md-12">

        <div class="card-box">
            <div class="card-block">
                <h6 class="card-title text-bold text-center">All Leaves</h6>

                <p class="content-group">

                </p>
                <a href="javascript:location.reload(true)" class="btn btn-success text-dark ml-auto mb-3 mb-sm-0">Refresh Leaves</a>
                <hr />
                <div class="table-responsive">
                    <table class="table table-border display table-striped custom-table  mb-0 " id="customerDatatable">
                        <thead>
                            <tr>
                                <th>SN</th>

                                <th>
                                    Employee Email
                                </th>
                                <th>
                                    Start Date
                                </th>
                                <th>
                                    End Date
                                </th>
                                <th>U.head</th>
                                <th>HR.</th>
                                <th>Status.</th>

                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.AllLeaves)
                            {
                                <tr>

                                    <td>
                                        <a asp-action="Details" asp-controller="Leaves" asp-route-id="@item.Id">
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </a>

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmployeeEmail)
                                    </td>
                                    <td> @Html.DisplayFor(modelItem => item.StartDate)</td>
                                    <td> @Html.DisplayFor(modelItem => item.EndDate)</td>
                                    <td>
                                        @if (item.UHeadStatus == true)
                                        {
                                            <span class="custom-badge status-orange">Approved</span>
                                        }
                                        else if (item.UHeadStatus == null)
                                        {
                                            <span class="custom-badge status-green"> Awaiting Approval</span>
                                        }
                                        else
                                        {
                                            <span class="custom-badge status-red">Disapproved</span>

                                        }
                                    </td>
                                    <td>
                                        @if (item.HRStatus == true)
                                        {
                                            <span class="custom-badge status-orange">Approved</span>
                                        }
                                        else if (item.HRStatus == null)
                                        {
                                            <span class="custom-badge status-green">Awaiting Approval</span>
                                        }
                                        else
                                        {
                                    <span class="custom-badge status-red">Disapproved</span>

                                        }
                                    </td>
                                    <td>
                                        @if (item.UHeadStatus == true && item.HRStatus == true)
                                        {
                                            <span class="custom-badge status-green">Approved</span>
                                        }
                                        else if (item.UHeadStatus == false && item.HRStatus == false)
                                        {
                                            <span class="custom-badge status-purple">Disapproved</span>
                                        }
                                        else
                                        {
                                            <span class="custom-badge status-orange">Undergoing Review</span>

                                        }
                                    </td>
                                    <td class="text-right">
                                        @if (item.HRStatus == null || item.Cancelled==false)
                                        {
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-database m-r-5"></i> Review</a>
                                                    @*<a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-eraser m-r-5"></i> Edit</a>*@
                                                    <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                                </div>
                                            </div>
                                        }
                                        else
                                        {
                                            <span class="custom-badge status-green">Disabled</span>
                                        }

                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

else
{
    <h4 class="text-danger">There are currently no leaves on the system yet from your unit, kindly check back later..</h4>
}



@section Scripts{
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/dataTables.bootstrap4.min.js"></script>

}

HrmsMgtApp/Views/Leaves/Index.cshtml
@model IEnumerable<Leave>

@{
    ViewData["Title"] = "Leaves List";
}

<link href="~/Preclinic-Hospital-Bootstrap4-Admin/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title"></h4>
    </div>
    <div class="col-sm-8 col-9 text-right m-b-20">
        <a asp-action="Create" class="btn btn-primary float-right btn-rounded"><i class="fa fa-plus"></i> Create Leave</a>
    </div>
</div>

@if (Model.Any())
{
    <div class="col-md-12">

        <div class="card-box">
            <div class="card-block">
                <h6 class="card-title text-bold text-center">All Leaves</h6>

                <p class="content-group">

                </p>
                <a href="javascript:location.reload(true)" class="btn btn-success text-dark ml-auto mb-3 mb-sm-0">Refresh Leaves</a>
                <hr />
                <div class="table-responsive">
                    <table class="table table-border display table-striped custom-table  mb-0 " id="customerDatatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                               
                                <th>
                                    Employee Email
                                </th>
                                <th>
                                    Start Date
                                </th>
                                <th>
                                    End Date
                                </th>
                                <th>U.head</th>
                                <th>HR.</th>
                                <th>Status.</th>

                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                 
                                    <td>
                                        <a asp-action="Details" asp-controller="Leaves" asp-route-id="@item.Id">
                                            @Html.DisplayFor(modelItem => item.Id)
                                        </a>

                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EmployeeEmail)
                                    </td>
                                    <td> @Html.DisplayFor(modelItem => item.StartDate)</td>
                                    <td> @Html.DisplayFor(modelItem => item.EndDate)</td>
                                    <td>
                                        @if (item.UHeadStatus == true)
                                        {
                                        <span class="custom-badge status-orange">Approved</span>
                                        }
                                        else if (item.UHeadStatus == null)
                                        {
                                        <span class="custom-badge status-green"> Awaiting Approval</span>
                                        }
                                        else
                                        {
                                        <span class="custom-badge status-red">Disapproved</span>

                                        }
                                    </td>
                                    <td>
                                        @if (item.HRStatus == true)
                                        {
                                        <span class="custom-badge status-orange">Approved</span>
                                        }
                                        else if (item.HRStatus == null)
                                        {
                                    <span class="custom-badge status-green">Awaiting Approval</span>
                                        }
                                        else
                                        {
                                    <span class="custom-badge status-orange">Undergoing Review</span>

                                        }
                                    </td>
                                    <td>
                                        @if (item.UHeadStatus == true && item.HRStatus==true)
                                        {
                                        <span class="custom-badge status-green">Approved</span>
                                        }
                                        else if (item.UHeadStatus == false && item.HRStatus == false)
                                        {
                                          <span class="custom-badge status-purple">Dissaproved</span>
                                        }
                                        else
                                        {
                                            <span class="custom-badge status-orange">Undergoing Review</span>

                                        }
                                    </td>
                                    <td class="text-right">
                                        @if (item.UHeadStatus==false)
                                        {
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-database m-r-5"></i> Details</a>
                                                    @*<a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-eraser m-r-5"></i> Edit</a>*@
                                                    <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                                </div>
                                            </div>
                                        }
                                        else if (item.UHeadStatus == null && item.HRStatus == null)
                                        {
                                            <div class="dropdown dropdown-action">
                                                <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                                <div class="dropdown-menu dropdown-menu-right">
                                                    <a class="dropdown-item" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-database m-r-5"></i> Details</a>
                                                    @*<a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-eraser m-r-5"></i> Edit</a>*@
                                                    <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                                </div>
                                            </div>
                                        }
                                        else
                                        {
                                            <span class="custom-badge status-green">Disabled</span>
                                        }

                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
}

else
{
    <h4 class="text-danger">You haven't applied for any Leave yet, kindly apply..</h4>
}



@section Scripts{
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/dataTables.bootstrap4.min.js"></script>

}