HrmsMgtApp/Controllers/UnitController.cs
using HrmsMgtApp.Data;
using HrmsMgtApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HrmsMgtApp.Controllers
{
    [Authorize(Roles = "UnitHead, DeptHead, Admin, SuperAdmin,HR")]
    public class UnitController : Controller
    {
        private readonly IUnit _unit;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public UnitController(IUnit unit,UserManager<ApplicationUser> userManager,
                                       SignInManager<ApplicationUser> signInManager)
        {
            _unit = unit;
            _userManager = userManager;
            _signInManager = signInManager;
        }
        // GET: UnitController
        public IActionResult Index()
        {
            var result = _unit.GetAllUnits();

            return View(result);
        }


        public IActionResult Info(int id)
        {
          var s=  _unit.GetUnit(id);

            var result = s.Users;

            var users = new UnitUsers()
            {
                Name = s.Name,
                Id=s.Id,
                Users=result
            };

            return View(users);
        }

        // GET: UnitController/Details/5
        public IActionResult Details(int id)
        {

            var result = _unit.GetUnit(id);
            if (result==null)
            {
                ViewBag.ErrorMessage = $"Department with id = {id} cannot be found";
                return View("ErrorPage");
            }


            return View(result);
        }

        // GET: UnitController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: UnitController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Unit model)
        {
            if (ModelState.IsValid)
            {
              await  _unit.Create(model);
              return  RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        // GET: UnitController/Edit/5
        public IActionResult Edit(int id)
        {
          var result=  _unit.GetUnit(id);
            if (result==null)
            {
                ViewBag.ErrorMessage = $"Unit with id = {id} cannot be found";
                return View("ErrorPage");
            }
            return View(result);
        }

        // POST: UnitController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Unit model)
        {
            if (ModelState.IsValid)
            {
              await  _unit.Edit(model);
                return RedirectToAction(nameof(Index));
            }
           
            return View(model);
        }

        // GET: UnitController/Delete/5
        public IActionResult Delete(int id)
        {
          var result=  _unit.GetUnit(id);

            if (result==null)
            {
                ViewBag.ErrorMessage = $"Unit with id = {id} cannot be found";
                return View("ErrorPage");
            }
            return View(result);
        }

        // POST: UnitController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

HrmsMgtApp/Views/Unit/Create.cshtml
@model Unit
@{
    ViewData["Title"] = "Create";
}


<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center">Create Unit.</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        

            <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back to Unit</a>
        
    </div>
</div>
<div class="row">
    <div class="col-lg-6 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
          
            <div class="m-t-20 text-center">
                <button class="btn btn-primary submit-btn">Create</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HrmsMgtApp/Views/Unit/Delete.cshtml
@model Unit
@{
    ViewData["Title"] = "Delete Unit";
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center">Delete Unit.</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>


        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back to Unit</a>

    </div>
</div>
<div class="row">
    <div class="col-lg-6 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <input asp-for="Id" hidden />
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" readonly/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input asp-for="CreatedOn" hidden />

            <div class="m-t-20 text-center">
                <button class="btn btn-danger submit-btn">Delete</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HrmsMgtApp/Views/Unit/Details.cshtml
@model Unit

@{
    ViewData["Title"] = "Unit Details";
}

<div>
    <h4 class="text-center">Unit Details</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedOn)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary btn-rounded"><i class="fa fa-edit"></i> Edit</a> 
    <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back</a>
</div>

HrmsMgtApp/Views/Unit/Edit.cshtml
@model Unit
@{
    ViewData["Title"] = "Edit Unit";
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center">Edit Unit.</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>


        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back to Unit</a>

    </div>
</div>
<div class="row">
    <div class="col-lg-6 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <input asp-for="Id" hidden/>
            <div class="form-group">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <input asp-for="CreatedOn" hidden/>

            <div class="m-t-20 text-center">
                <button class="btn btn-primary submit-btn">Update</button>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HrmsMgtApp/Views/Unit/Index.cshtml
@model IEnumerable<Unit>

@{
    ViewData["Title"] = "Unit Page";
}

<link href="~/Preclinic-Hospital-Bootstrap4-Admin/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title"></h4>
    </div>
    <div class="col-sm-8 col-9 text-right m-b-20">
        <a asp-action="Create" class="btn btn-primary float-right btn-rounded"><i class="fa fa-plus"></i> Add Unit</a>
    </div>
</div>

@if (Model.Any())
{

    <div class="col-md-12">

        <div class="card-box">
            <div class="card-block">
                <h6 class="card-title text-bold text-center">All Units</h6>

                <p class="content-group">

                </p>
                <a href="javascript:location.reload(true)" class="btn btn-success text-dark ml-auto mb-3 mb-sm-0">Refresh Unit</a>
                <hr />
                <div class="table-responsive">
                    <table class="table table-border display table-striped custom-table  mb-0 " id="customerDatatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Created On
                                </th>

                                <th>Action</th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td> @Html.DisplayFor(modelItem => item.Id)</td>
                                    <td>
                                        <a asp-action="Info" asp-controller="Unit" asp-route-id="@item.Id">
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </a>
                                       
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.CreatedOn)
                                    </td>
                                    <td class="text-right">
                                        <div class="dropdown dropdown-action">
                                            <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <a class="dropdown-item" asp-action="Details" asp-route-id="@item.Id"><i class="fa fa-database m-r-5"></i> Details</a>
                                                <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-eraser m-r-5"></i> Edit</a>
                                                <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                            </div>
                                        </div>
                                    </td>

                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


}
else
{
    <h4 class="text-info">There are currently no user's in the system</h4>

}

@section Scripts{ 
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/dataTables.bootstrap4.min.js"></script>

}

HrmsMgtApp/Views/Unit/Info.cshtml
@model UnitUsers
@{
    ViewData["Title"] = "Info";
}


<link href="~/Preclinic-Hospital-Bootstrap4-Admin/assets/css/dataTables.bootstrap4.min.css" rel="stylesheet" />
<div class="row">
    <div class="col-sm-4 col-3">
        <h4 class="page-title">All users in @Model.Name Department</h4>
    </div>
    <div class="col-sm-8 col-9 text-right m-b-20">
      
        <a asp-action="Index"  class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back to Unit</a>
    </div>
</div>

@if (Model.Users.Any())
{

    <div class="col-md-12">

        <div class="card-box">
            <div class="card-block">
                <h6 class="card-title text-bold text-center">All Users</h6>

                <p class="content-group">

                </p>
               
                <hr />
                <div class="table-responsive">
                    <table class="table table-border display table-striped custom-table  mb-0 " id="customerDatatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>
                                    Name
                                </th>
                                <th>
                                    Phone Number
                                </th>
                                <th>
                                    Created On
                                </th>


                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Users)
                            {
                            <tr>
                                <td> @Html.DisplayFor(modelItem => item.Id)</td>
                                <td>
                                    <a asp-action="Details" asp-controller="User" asp-route-id="@item.Id">
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </a>

                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.PhoneNumber)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedOn)
                                </td>
                             

                            </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


}
else
{
    <h4 class="text-info">There are currently no user's in the system</h4>

}

@section Scripts{
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/jquery.dataTables.min.js"></script>
    <script src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/js/dataTables.bootstrap4.min.js"></script>

}