HrmsMgtApp/Controllers/LeaveTypeController.cs
using HrmsMgtApp.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HrmsMgtApp.Controllers
{
    [Authorize]
    public class LeaveTypeController : Controller
    {
        private readonly ILeaveTypes _leaveTypesService;

        public LeaveTypeController(ILeaveTypes leaveTypesService)
        {
            _leaveTypesService = leaveTypesService;
        }
        // GET: LeaveTypeController
        public IActionResult Index()
        {
            var result = _leaveTypesService.GetAllLeaves();
            return View(result);
        }

        // GET: LeaveTypeController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: LeaveTypeController/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: LeaveTypeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(LeaveType model)
        {
            if (ModelState.IsValid)
            {
               await _leaveTypesService.Create(model);

                return RedirectToAction(nameof(Index));

            }

            return View(model);
        }

        // GET: LeaveTypeController/Edit/5
        public IActionResult Edit(int id)
        {
          var result=  _leaveTypesService.GetLeaveType(id);
            if (result==null)
            {
                ViewBag.ErrorMessage = $"Leave Type with id = {id} cannot be found";
                return View("ErrorPage");
            }
            return View(result);
        }

        // POST: LeaveTypeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(LeaveType model)
        {
            if (ModelState.IsValid)
            {
               
              await  _leaveTypesService.Update(model);
                return RedirectToAction(nameof(Index));

            }

            return View(model);
        }

        // GET: LeaveTypeController/Delete/5
        [HttpGet]
        public IActionResult Delete(int id)
        {
          var result=  _leaveTypesService.GetLeaveType(id);
            if (result==null)
            {
                ViewBag.ErrorMessage = $"Leave Type with id = {id} cannot be found";
                return View("ErrorPage");
            }
            return View(result);
        }

        // POST: LeaveTypeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(LeaveType model)
        {
             await  _leaveTypesService.Delete(model.Id);

            return RedirectToAction(nameof(Index));

        }
    }
}

HrmsMgtApp/Views/LeaveType/Create.cshtml
@model LeaveType
@inject UserManager<ApplicationUser> userManager

@{
    ViewData["Title"] = "Create Leave";
    var user = await userManager.GetUserAsync(User);
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center">Add Leave Type</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Create">
            <div class="form-group">
                <label asp-for="Type"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea cols="30" rows="4" class="form-control" asp-for="Description" placeholder="Enter description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDays"></label>
                <input asp-for="NumberOfDays" class="form-control" min="0"/>
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <input asp-for="AddedBy" value="@user.UserName" hidden />
            <div class="m-t-20 text-center">
                <button class="btn btn-primary submit-btn">Create</button>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HrmsMgtApp/Views/LeaveType/Delete.cshtml
@model LeaveType
@{
    ViewData["Title"] = "Delete";
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center text-danger">Are you sure you want to delete this?</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Delete">
            <input asp-for="Id" hidden/>
            <div class="form-group">
                <label asp-for="Type"></label>
                <input asp-for="Type" class="form-control" readonly/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea cols="30" rows="4" class="form-control" asp-for="Description" placeholder="Enter description" readonly></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDays"></label>
                <input asp-for="NumberOfDays" class="form-control" min="0" readonly/>
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
           
            <div class="m-t-20 text-center">
                <button class="btn btn-danger submit-btn">Delete</button>
            </div>
        </form>
    </div>
</div>

HrmsMgtApp/Views/LeaveType/Edit.cshtml
@model LeaveType
@inject UserManager<ApplicationUser> _userManager
@{
    ViewData["Title"] = "Edit Leave";
    var user =await _userManager.GetUserAsync(User);
}

<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h4 class="page-title text-center">Edit Leave Type</h4>
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <a asp-action="Index" class="btn btn-primary float-right btn-rounded"><i class="fa fa-backward"></i> Back</a>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 offset-lg-2">
        <form method="post" enctype="multipart/form-data" asp-action="Edit">
            <input asp-for="Id" hidden/>
            <div class="form-group">
                <label asp-for="Type"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description"></label>
                <textarea cols="30" rows="4" class="form-control" asp-for="Description" placeholder="Enter description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfDays"></label>
                <input asp-for="NumberOfDays" class="form-control" min="0" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <input asp-for="AddedBy" value="@user.UserName" hidden />
            <div class="m-t-20 text-center">
                <button class="btn btn-primary submit-btn">Update</button>
            </div>
        </form>
    </div>
</div>

HrmsMgtApp/Views/LeaveType/Index.cshtml
@model IEnumerable<LeaveType>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-sm-8 col-5">
        <h4 class="page-title">Leave Type</h4>
    </div>
    <div class="col-sm-4 col-7 text-right m-b-30">
        <a asp-action="Create" asp-controller="LeaveType" class="btn btn-primary btn-rounded float-right"><i class="fa fa-plus"></i> Add Leave Type</a>
    </div>
</div>

@if (Model.Any())
{
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                <table class="table table-striped custom-table">
                    <thead>
                        <tr>
                            <th>SN</th>
                            <th>Leave Type</th>
                            <th>Leave Days</th>
                            <th>Date Created</th>
                            <th>Created By</th>
                            <th class="text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @item.Id
                                </td>
                                <td>@item.Type</td>
                                <td>@item.NumberOfDays</td>
                                <td>@item.CreatedBy</td>
                                <td>@item.AddedBy</td>                           
                                <td class="text-right">
                                    <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" asp-action="Edit" asp-route-id="@item.Id"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                            <a class="dropdown-item" asp-action="Delete" asp-route-id="@item.Id"><i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

else
{
    <h4 class="text-info">There are currently no Leave type in the system</h4>
}