HrmsMgtApp/Controllers/EmployeeBioController.cs
using HrmsMgtApp.Data;
using HrmsMgtApp.Models;
using HrmsMgtApp.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace HrmsMgtApp.Controllers
{
    [Authorize]
    public class EmployeeBioController : Controller
    {
        private readonly IEmployeeBio _employeeBioService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public EmployeeBioController(IEmployeeBio employeeBioService, UserManager<ApplicationUser> userManager,
                                          IWebHostEnvironment hostingEnvironment)
        {
            _employeeBioService = employeeBioService;
            _userManager = userManager;
            _hostingEnvironment = hostingEnvironment;
        }
        // GET: EmployeeBioController
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);

            var Userbio = _employeeBioService.GetEmployee(user.Id);

            if (Userbio==null)
            {
                ViewBag.ErrorMessage = $"userbio with id = {user.Id} cannot be found, Kindly complete your registration";
                return View("ErrorPage");
            }
            return View(Userbio);
        }

        // GET: EmployeeBioController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: EmployeeBioController/Create
        public IActionResult Create()
        {
            var s = new EmployeeBioVm();
            return View(s);
        }

        // POST: EmployeeBioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeBioVm model)
        {
            if (ModelState.IsValid)
            {
                EmployeeBioData data = new EmployeeBioData()
                {
                    EmployeeId=model.EmployeeId,
                    FirstName=model.FirstName,
                    LastName=model.LastName,
                    BloodGroup=model.BloodGroup,
                    DOB=model.DOB,
                    CUG=model.CUG,
                    EmployeeNo=model.EmployeeNo,
                    ModeOfEmployment=model.ModeOfEmployment,
                    DateOfEmployment=model.DateOfEmployment,
                    YearsOfExperience=model.YearsOfExperience,
                    Designation=model.Designation,
                    MaritalStatus=model.MaritalStatus,
                    Address=model.Address,
                    CountryOfOrigin=model.CountryOfOrigin,
                    BeneficiaryName=model.BeneficiaryName,
                    BeneficiaryAddress=model.BeneficiaryAddress,
                    BeneficiaryNo=model.BeneficiaryNo,
                    EmergencyName=model.EmergencyName,
                    EmergencyAddress=model.EmergencyAddress,
                    Lgas=model.Lgas,
                    States=model.States,
                    Region=model.Region,
                    City=model.City,
                    Academic=model.Academic,
                    AcademicDescription=model.AcademicDescription,
                    Professional=model.Professional,
                    ProfessionalDescription=model.ProfessionalDescription,
                    Institution=model.Institution,
                    Duration=model.Duration,
                    StartDate=model.StartDate,
                    EndDate=model.EndDate,
                    AddedBy=model.AddedBy,
                    Gender= (Gender)model.Sex,
                    CreatedDate=model.CreatedDate
                };



                if (model.Image != null && model.Image.Length > 0)
                {
                    var uploadDir = @"images/Cert";
                    var fileName = Path.GetFileNameWithoutExtension(model.Image.FileName);
                    var extension = Path.GetExtension(model.Image.FileName);
                    var webRootPath = _hostingEnvironment.WebRootPath;
                    fileName = model.FirstName + fileName + extension;
                    var path = Path.Combine(webRootPath, uploadDir, fileName);
                    await model.Image.CopyToAsync(new FileStream(path, FileMode.Create));
                    data.Image = "/" + uploadDir + "/" + fileName;
                }

                await   _employeeBioService.Create(data);
             return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        // GET: EmployeeBioController/Edit/5
        public IActionResult Edit(int id)
        {
            var result = _employeeBioService.GetEmployeeBio(id);

            if (result==null)
            {
                ViewBag.ErrorMessage = $"userbio with id = {id} cannot be found";
                return View("ErrorPage");
            }


            EmployeeEditBioVm bioVm = new EmployeeEditBioVm()
            {
                Id=result.Id,
                EmployeeId=result.EmployeeId,
                FirstName=result.FirstName,
                LastName=result.LastName,
                BloodGroup=result.BloodGroup,
                DOB=result.DOB,
                CUG=result.CUG,
                EmployeeNo=result.EmployeeNo,
                ModeOfEmployment=result.ModeOfEmployment,
                DateOfEmployment=result.DateOfEmployment,
                YearsOfExperience=result.YearsOfExperience,
                Designation=result.Designation,
                MaritalStatus=result.MaritalStatus,
                Address=result.Address,
                CountryOfOrigin=result.CountryOfOrigin,
                BeneficiaryName=result.BeneficiaryName,
                BeneficiaryNo=result.BeneficiaryNo,
                BeneficiaryAddress=result.BeneficiaryAddress,
                EmergencyName=result.EmergencyName,
                EmergencyNo=result.EmergencyNo,
                EmergencyAddress=result.EmergencyAddress,
                Lgas=result.Lgas,
                States=result.States,
                Region=result.Region,
                City=result.City,
                Academic=result.Academic,
                AcademicDescription=result.AcademicDescription,
                Professional=result.Professional,
                ProfessionalDescription=result.ProfessionalDescription,
                Institution=result.Institution,
                ExistingPhotoPath=result.Image,
                Duration=result.Duration,
                StartDate=result.StartDate,
                EndDate=result.EndDate,
                AddedBy=result.AddedBy,
                CreatedDate=result.CreatedDate,
                Sex= (Sex)result.Gender,
                
            };

            return View(bioVm);
        }

        // POST: EmployeeBioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EmployeeEditBioVm model)
        {

            if (ModelState.IsValid)
            {
                var s = _employeeBioService.GetEmployeeBio(model.Id);

                if (s == null)
                {
                    ViewBag.ErrorMessage = $"userbio with id = {s.Id} cannot be found";
                    return View("ErrorPage");
                }

                s.Id = model.Id;
                s.EmployeeId = model.EmployeeId;
                s.FirstName = model.FirstName;
                s.LastName = model.LastName;
                s.BloodGroup = model.BloodGroup;
                s.DOB = model.DOB;
                s.CUG = model.CUG;
                s.EmployeeNo = model.EmployeeNo;
                s.ModeOfEmployment = model.ModeOfEmployment;
                s.DateOfEmployment = model.DateOfEmployment;
                s.YearsOfExperience = model.YearsOfExperience;
                s.Designation = model.Designation;
                s.MaritalStatus = model.MaritalStatus;
                s.Address = model.Address;
                s.CountryOfOrigin = model.CountryOfOrigin;
                s.BeneficiaryName = model.BeneficiaryName;
                s.BeneficiaryNo = model.BeneficiaryNo;
                s.BeneficiaryAddress = model.BeneficiaryAddress;
                s.EmergencyName = model.EmergencyName;
                s.EmergencyNo = model.EmergencyNo;
                s.EmergencyAddress = model.EmergencyAddress;
                s.Lgas = model.Lgas;
                s.States = model.States;
                s.Region = model.Region;
                s.City = model.City;
                s.Academic = model.Academic;
                s.AcademicDescription = model.AcademicDescription;
                s.Professional = model.Professional;
                s.ProfessionalDescription = model.ProfessionalDescription;
                s.Institution = model.Institution;
                //s.Image = model.ExistingPhotoPath;
                s.Duration = model.Duration;
                s.StartDate = model.StartDate;
                s.EndDate = model.EndDate;
                s.AddedBy = model.AddedBy;
                s.Gender = (Gender)model.Sex;

               

                if (model.Image != null && model.Image.Length > 0)
                {
                    if (model.ExistingPhotoPath != null)
                    {
                        string filepath = Path.Combine(_hostingEnvironment.WebRootPath, model.ExistingPhotoPath);
                        System.IO.File.Delete(filepath);
                    }
                    var uploadDir = @"images/Cert";
                    var fileName = Path.GetFileNameWithoutExtension(model.Image.FileName);
                    var extension = Path.GetExtension(model.Image.FileName);
                    var webRootPath = _hostingEnvironment.WebRootPath;

HrmsMgtApp/Views/EmployeeBio/Index.cshtml
@model EmployeeBioData
@inject UserManager<ApplicationUser> userManager


@{
    ViewData["Title"] = "Employee-Bio";
    var photopath = "~/images/Cert/" + (Model.Image ?? "user.jpg");
    var user = await userManager.GetUserAsync(User);
}


<div class="row">
    <div class="col-sm-7 col-6">
        <h4 class="page-title">@Model.FirstName Bio-Data</h4>
    </div>

    <div class="col-sm-5 col-6 text-right m-b-30">
        <a asp-action="Edit" asp-controller="EmployeeBio" asp-route-id="@Model.Id" class="btn btn-primary btn-rounded"><i class="fa fa-edit"></i> Edit</a>
    </div>
</div>
<div class="card-box profile-header">
    <div class="row">
        <div class="col-md-12">
            <div class="profile-view">
                <div class="profile-img-wrap">
                    <div class="profile-img">

                        <a href="#"><img class="avatar" src="@user.ProfileImageUrl" alt="" asp-append-version="true"></a>
                    </div>

                </div>
                <div class="profile-basic">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="profile-info-left">
                                <h3 class="user-name m-t-0 mb-0">@Model.FirstName @Model.LastName</h3>
                                <small class="text-muted">@Model.Designation</small>
                                <div class="staff-id">Employee ID : @Model.EmployeeId</div>

                            </div>
                        </div>
                        <div class="col-md-7">
                            <ul class="personal-info">
                                <li>
                                    <span class="title">Gender:</span>
                                    <span class="text"><a href="#">@Model.Gender</a></span>
                                </li>
                                <li>
                                    <span class="title">Status:</span>
                                    <span class="text"><a href="#">@Model.MaritalStatus</a></span>
                                </li>
                                <li>
                                    <span class="title">Birthday:</span>
                                    <span class="text">@Model.DOB</span>
                                </li>
                                <li>
                                    <span class="title">Date Created:</span>
                                    <span class="text">@Model.CreatedDate</span>
                                </li>
                                <li>
                                    <span class="title">Address:</span>
                                    <span class="text">@Model.Address</span>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="profile-tabs">
    <ul class="nav nav-tabs nav-tabs-bottom">
        <li class="nav-item"><a class="nav-link active" href="#about-cont" data-toggle="tab">About</a></li>
        <li class="nav-item"><a class="nav-link" href="#bottom-tab2" data-toggle="tab">Other Information</a></li>

    </ul>

    <div class="tab-content">
        <div class="tab-pane show active" id="about-cont">
            <div class="row">
                <div class="col-md-12">
                    <div class="card-box">
                        <h3 class="card-title">Education Informations</h3>
                        <div class="experience-box">
                            <ul class="experience-list">
                                <li>
                                    <div class="experience-user">
                                        <div class="before-circle"></div>
                                    </div>
                                    <div class="experience-content">
                                        <div class="timeline-content">
                                            <a href="#/" class="name">@Model.Institution</a>
                                            <div>@Model.Academic</div>
                                            <span class="time">2001 - 2003</span>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                            <ul class="experience-list">
                                <li>
                                    <div class="experience-user">
                                        <div class="before-circle"></div>
                                    </div>
                                    <div class="experience-content">
                                        <div class="timeline-content">
                                            <a href="#/" class="name">@Model.Professional</a>
                                            <div>@Model.ProfessionalDescription</div>
                                            <span class="time">2001 - 2003</span>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </div>
                    <div class="card-box mb-0">
                        <h3 class="card-title">Experience</h3>
                        <div class="experience-box">
                            <ul class="experience-list">
                                <li>
                                    <div class="experience-user">
                                        <div class="before-circle"></div>
                                    </div>
                                    <div class="experience-content">
                                        <div class="timeline-content">
                                            <a href="#/" class="name">@Model.Designation</a>
                                            <span class="time">Jan 2019 - Present( @Model.YearsOfExperience) </span>
                                        </div>
                                    </div>
                                </li>

                                <li>
                                    <div class="experience-user">
                                        <div class="before-circle"></div>
                                    </div>
                                    <div class="experience-content">
                                        <div class="timeline-content">
                                            <a href="#/" class="name">Software Engineer </a>
                                            <span class="time">Jan 2004 - Present (5 years 2 months)</span>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-box mb-0">
                        <h3 class="card-title">Certificate</h3>
                        <div class="experience-box">

                            <a href="#"><img class="" src="@Model.Image" alt="Cert" style="border-radius:5px; border:1px solid #bbb9b9; width:30%;" asp-append-version="true"></a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="bottom-tab2">


            <ul class="personal-info">
                <li>
                    <span class="title">State:</span>
                    <span class="text"><a href="#">@Model.States</a></span>
                </li>
                <li>
                    <span class="title">LGA:</span>
                    <span class="text"><a href="#">@Model.Lgas</a></span>
                </li>
                <li>
                    <span class="title">Beneficiary Name:</span>
                    <span class="text">@Model.BeneficiaryName</span>
                </li>
                <li>
                    <span class="title">Beneficiary Contact:</span>
                    <span class="text">@Model.BeneficiaryNo</span>
                </li>
                <li>
                    <span class="title">Beneficiary Adress:</span>
                    <span class="text">@Model.BeneficiaryAddress</span>
                </li>
            </ul>

        </div>

    </div>
</div>

@if (user.ProfileImageUrl == null)
{
    <form id="profile-form" method="post" enctype="multipart/form-data" asp-action="UploadImage" asp-controller="User">

        <div class="form-group">
            <label>Profile Picx</label>
            <div class="profile-upload">
                <div class="upload-img">
                    <img alt="" src="~/Preclinic-Hospital-Bootstrap4-Admin/assets/img/user.jpg">
                </div>
                <div class="upload-input">
                    <input type="file" name="file" class="form-control">
                </div>
            </div>

            <hr />

        </div>
        <button id="update-profile-button" type="submit" class="btn btn-primary">Save</button>
    </form>
}